#ifndef STATISTICSVIEW_GLOBAL_H
#define STATISTICSVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STATISTICSVIEW)
#  define STATISTICSVIEWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STATISTICSVIEWSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STATISTICSVIEW_GLOBAL_H
